services:
  - docker:dind

stages:
  - test

test:
  stage: test
  image: golang:1.22
  services:
   - name: docker:dind
     alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - go test ./...
  only:
    - main
    - merge_requests

